import React from 'react'

import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
     
        {children}
        <footer
          style={{
            backgroundColor: "#0f172a",
            color: "#cbd5e1",
            padding: "25px 40px",
            textAlign: "center",
            marginTop: "50px",
          }}
        >
          <p style={{ margin: "8px 0 0", fontSize: "14px" }}>
            Built with Next.js
          </p>
        </footer>
      </body>
    </html>
  );
}
